version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(deps)
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(deps)
    exclude-paths:
      - test/fixtures/**
    groups:
      minor-and-patch:
        update-types: [minor, patch]
